# Generated by Django 6.0.4 on 2026-04-10 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso operacional'), ('FINANCIAMIENTO', 'Financiamiento'), ('EXCLUIR', 'Excluir')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta banco',
                'verbose_name_plural': 'Cuentas banco',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('mov_debe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mov_haber', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('cajcod', models.CharField(blank=True, default='', max_length=20)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='flujo.concepto')),
                ('cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='flujo.cuentabanco')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
