# Generated by Django 6.0.4 on 2026-04-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_movimiento_cpbnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecciones', to='flujo.concepto')),
            ],
            options={
                'verbose_name': 'Proyección',
                'verbose_name_plural': 'Proyecciones',
                'ordering': ['anio', 'mes', 'concepto__codigo', 'id'],
            },
        ),
    ]
