# Generated by Django 6.0.4 on 2026-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0003_proyeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='origen_clave',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='origen_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
