# Generated by Django 6.0.4 on 2026-04-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0004_movimiento_origen_clave_movimiento_origen_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial_base', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('money_market_inicial_base', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración flujo',
                'verbose_name_plural': 'Configuración flujo',
            },
        ),
    ]
