# Generated by Django 6.0.4 on 2026-04-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0005_configuracionflujo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyeccion',
            options={'ordering': ['anio', 'mes', 'concepto__codigo', 'origen', 'id'], 'verbose_name': 'Proyección', 'verbose_name_plural': 'Proyecciones'},
        ),
        migrations.AddField(
            model_name='proyeccion',
            name='origen',
            field=models.CharField(choices=[('REAL', 'Real'), ('PROYECTADO', 'Proyectado')], db_index=True, default='PROYECTADO', max_length=20),
        ),
    ]
