# Generated by Django 6.0.4 on 2026-04-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0006_alter_proyeccion_options_proyeccion_origen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionflujo',
            options={'verbose_name': 'ConfiguraciÃ³n flujo', 'verbose_name_plural': 'ConfiguraciÃ³n flujo'},
        ),
        migrations.AlterModelOptions(
            name='proyeccion',
            options={'ordering': ['anio', 'mes', 'concepto__codigo', 'origen', 'id'], 'verbose_name': 'ProyecciÃ³n', 'verbose_name_plural': 'Proyecciones'},
        ),
    ]
